### ISSUE TITLE
Due Date - Project Requirements

### ISSUE THREAD

**Issue by PrimalOrB** [PrimalOrB/find_your_drink#20]
Project Requirements as laid out in Bootcampspot
- [x] Use a CSS framework other than Bootstrap. #1 
- [x] Be deployed to GitHub Pages. #18 
- [x] Be interactive (i.e., accept and respond to user input). #1 
- [x] Use at least two server-side APIs. #2  #4  #6  
- [x] Does not use alerts, confirms, or prompts (use modals). #1  #10
- [x] Use client-side storage to store persistent data. #13 #23
- [x] Be responsive. #1  #10 
- [x] Have a polished UI. #1  #10 
- [x] Have a clean repository that meets quality coding standards (file structure, naming conventions, follows best practices for class/id naming conventions, indentation, quality comments, etc.).
- [x] Have a quality README (with unique name, description, technologies used, screenshot, and link to deployed application). #17 
- [x] Finally, you must add your project to the portfolio that you created in Module 2. #19

**Comment by Mantablast** [comment]
Added the project to my portfolio
